---
output:
  word_document: default
  pdf_document: default
---
IST 687  
Homework 4   
Due Date: 11/2  

**Code requires the following packages to run**

```{r}
library(moments) #install.packages("moments")
library(scales) #install.packages("scales")
```

**Step 1: Write a summarizing function to understand the distribution of a vector**  

```{r}
#create function that calculates descriptive characteristics for a vector
printVecInfo <- function(vector){
print(mean(vector)) #a. mean
print(median(vector)) #b. median
print(min(vector)) #c. min
print(max(vector)) #d. max
print(sd(vector)) #e. st dev
print(quantile(vector, probs = c(0.05, 0.95))) #quantiles
print(skewness(vector))} #skewness

#test the function with a vector
testVector1 <- c(1,2,3,4,5,6,7,8,9,10,50)
printVecInfo(testVector1)
```

**Step 2: Creating Samples in a Jar**

```{r}
#4. create a variable 'jar' that has 50 red and 50 blue marbles
jarRed <- replicate(50, "red", simplify = TRUE)
jarBlue <- replicate(50, "blue", simplify = TRUE)
jar <- c(jarRed, jarBlue)

#5. confirm there are 50 reds by summing the samples that are red
sum(jar=="red")

#6. Sample 10 'marbles' (really strings) from the jar. How many are red? What was the percentage of red marbles?
sum(sample(jar, 10, replace=TRUE)=="red") #Sum total number of red marbles from our sample
length(sample(jar, 10, replace=TRUE)) #total number of marbles in the sample
percent(sum(sample(jar, 10, replace=TRUE)=="red")/length(sample(jar, 10, replace=TRUE))) #Percent of marbles that are red out of the entire sample

#7. Do the sampling 20 times, using the 'replicate' command. This should generate a list of 20 numbers. Each number is the mean of how many reds there were in 10 samples. Use your printVecInfo to see information of the samples. Also generate a histogram of the samples.

#List of 20 numbers each of which represents how many reds there were in our n=10 sample of jar
replicate(20, sum(sample(jar, size = 10, replace=TRUE) == "red"),simplify=TRUE)

#Descriptive statistics on the 20 repetitions in previous step (slightly different due to randomness)
printVecInfo(replicate(20, sum(sample(jar, size = 10, replace=TRUE) == "red"),simplify=TRUE))

#Histogram visualization on the 20 repetitions in the previous step (slightly different due to randomness)
hist(replicate(20, sum(sample(jar, size = 10, replace=TRUE) == "red"),simplify=TRUE)) 

#8. Repeat #7, but this time, sample the jar 100 times. You should get 20 numbers, this time each number represents the mean of how many reds there were in the 100 samples. Use your printVecInfo to see information of the samples. Also generate a histogram of the samples.

#List of 20 numbers each of which represents how many reds there were in our n=100 sample of jar
replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE)

#Descriptive statistics on the 20 repetitions in previous step (slightly different due to randomness)
printVecInfo(replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE))

#Histogram visualization on the 20 repetitions in the previous step (slightly different due to randomness)
hist(replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE))

#9. Repeat #8, but this time, replicate the sampling 100 times. You should get 100 numbers, this time each number represents the mean of how many reds there were in the 100 samples. Use your printVecInfo to see information of the samples. Also generate a histogram of the samples.

#List of 100 numbers each of which represents how many reds there were in our n=100 sample of jar
replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE)

#Descriptive statistics on the 100 repetitions in previous step (slightly different due to randomness)
printVecInfo(replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE))

#Histogram visualization on the 20 repetitions in the previous step (slightly different due to randomness)
hist(replicate(20, sum(sample(jar, size = 100, replace=TRUE) == "red"),simplify=TRUE))
```

**Step 3: Explore the airquality dataset**

```{r}
#10. Store the 'airquality' dataset into a temporary variable
airquality <- airquality

#11. clean the dataset (i.e. remove the NAs)
airqualitycleaned <- na.omit(airquality)

#12. Explore Ozone, Wind and Temp by doing a 'prntVecInfo' on each as well as generating a histogram for each

#printVecInfo on Ozone and histogram
printVecInfo(airqualitycleaned$Ozone)
hist(airqualitycleaned$Ozone)

#printVecInfo on Wind and histogram
printVecInfo(airqualitycleaned$Wind)
hist(airqualitycleaned$Wind)

#printVecInfo on Temp and histogram
printVecInfo(airqualitycleaned$Temp)
hist(airqualitycleaned$Temp)
```